/** AUTO-GENERATED by JCEF TypeScriptObjectProcessor – DO NOT EDIT **/
import {ResponseType} from "./ResponseType";
import {ResponseValueConverter} from "./ResponseValueConverter";

export class CefRestService {
    static request<T>(className: string, methodName: string, parameters: object, responseType: ResponseType): Promise<any> {
        const targetUrl = '$host:$port';

        const requestBody = {
            className,
            methodName,
            parameters
        };

        return fetch(targetUrl, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify(requestBody),
        })
            .then(response => {
                if (!response.ok) {
                    throw new Error(`HTTP error! Status: ${response.status} ${response.statusText}`);
                }

                return response.text();
            })
            .then(rawText => {
                return ResponseValueConverter.convert<T>(rawText, responseType);
            })
            .catch(error => {
                console.error('Error during POST request:', error);
                throw error;
            });
    };
}