package io.github.bitfist.jcef.spring.tsobject.internal.processor;

class TypeScriptEnumGenerator {

	public String generate(TSClass tsClass) {
		var buffer = new StringBuilder();

		// Header comment
		buffer.append("/** AUTO-GENERATED by JCEF TypeScriptProcessor – DO NOT EDIT **/\n\n");

		// Generate TypeScript enum with string values
		buffer.append("export enum ").append(tsClass.getTsClassName()).append(" {\n");

		// Generate enum constants with string values
		for (Field field : tsClass.getFields()) {
			buffer.append("    ").append(field.name()).append(" = '").append(field.name()).append("',\n");
		}

		buffer.append("}\n");

		return buffer.toString();
	}
}