package io.github.bitfist.jcef.spring.query.internal.processor;

import java.io.BufferedWriter;
import java.io.IOException;

/**
 * 📝 Renders the auto-generated banner and import section for TS files.
 */
final class HeaderRenderer {

    void render(BufferedWriter writer, int depth) throws IOException {
        String rel = depth == 0 ? "./" : "../".repeat(depth);
        writer.write("/** AUTO‑GENERATED by JCEF TypeScriptGeneratorProcessor – DO NOT EDIT **/\n");
        writer.write("import { CefQueryService } from '" + rel + "cef/CefQueryService';\n");
        writer.write("import type { ResponseType } from '" + rel + "cef/CefQueryService';\n\n");
    }
}
