name: Renovate
on:
  schedule:
    - cron: '45 * * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: renovatebot/github-action@v36
        with:
          token: ${{ secrets.GITHUB_TOKEN }}